import React from "react";
import "./PrivacyPolicy.scss";
import { Navbar } from "@/Components";

function PrivacyPolicy() {
  return (
    <div className="mainPrivacyContainer">
      <Navbar hidePageButtons={true}/>
      <div className="contentContainer">
        <h5>Privacy Policy</h5>
        <div className="introTextContainer">
          <p>
            THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION
            TECHNOLOGY ACT, 2000 AND RULES THERE UNDER AS APPLICABLE AND THE
            AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS
            STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS
            ELECTRONIC RECORD IS GENERATED BY THE COMPUTER SYSTEM AND DOES NOT
            REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURE.
          </p>
          <div id="comp-lgxfvcx6" data-testid="richTextElement">
            <p>
              IN THIS AGREEMENT, THE TERMS &quot;WE/US/OUR/BIDRYDE&quot; REFER
              INDIVIDUALLY AND COLLECTIVELY TO BIDRYDE MOBILITY TECHNOLOGIES
              PRIVATE LIMITED, WHILE THE TERMS &quot;YOU/YOUR/YOURSELF&quot;
              REFER TO THE USERS AND MEMBERS OF THE SITE.
            </p>
          </div>
          <div
            id="comp-lgxldro1"
            class="c9GqVL QxJLC3 comp-lgxldro1 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              YOU AND BIDRYDE ARE BOUND LEGALLY TO ONE ANOTHER BY THIS PRIVACY
              POLICY, WHICH IS A LEGALLY BINDING DOCUMENT (BOTH TERMS DEFINED
              ABOVE).
            </p>
          </div>
          <div
            id="comp-lgwao6lw"
            class="c9GqVL QxJLC3 comp-lgwao6lw wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              THIS DOCUMENT IS PUBLISHED AND SHALL BE CONSTRUED IN ACCORDANCE
              WITH THE PROVISIONS OF THE INFORMATION TECHNOLOGY (REASONABLE
              SECURITY PRACTICES AND PROCEDURES AND SENSITIVE PERSONAL DATA OF
              INFORMATION) RULES, 2011 UNDER INFORMATION TECHNOLOGY ACT, 2000;
              THAT REQUIRE PUBLISHING OF THE PRIVACY POLICY FOR COLLECTION, USE,
              STORAGE AND TRANSFER OF SENSITIVE PERSONAL DATA OR INFORMATION.
            </p>
          </div>
          <div
            id="comp-lgxfrux8"
            class="c9GqVL QxJLC3 comp-lgxfrux8 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY USING THE WEBSITE OR
              MOBILE APPLICATIONS, YOU ACKNOWLEDGE THAT YOU HAVE READ, AGREE
              WITH, AND CONSENT TO THIS PRIVACY POLICY. DO NOT USE THIS WEBSITE
              OR MOBILE APPLICATION IF YOU DO NOT AGREE WITH THE TERMS OF THIS
              PRIVACY POLICY. YOU HEREBY GIVE YOUR UNCONDITIONAL AND IRREVOCABLE
              CONSENT TO BIDRYDE FOR THE PURPOSES PERMITTED UNDER INCLUDING BUT
              NOT LIMITED TO THE PROVISIONS OF SECTIONS 43A, 72, AND SECTION 72A
              OF THE INFORMATION TECHNOLOGY ACT, 2000.
            </p>
          </div>
          <div
            id="comp-lgxlnmaz"
            class="c9GqVL QxJLC3 comp-lgxlnmaz wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              This Privacy Policy (the &quot;
              <span style={{ fontWeight: "bold" }}>Policy</span>
              &quot;) describes how BIDRYDE collects, uses, protects, and shares
              any information you give us when you use this website, i.e.,{" "}
              <a
                data-auto-recognition="true"
                href="http://www.bidryde.in"
                target="_blank"
              >
                www.bidryde.in
              </a>
              , and its mobile application (collectively referred to as &quot;
              <span style={{ fontWeight: "bold" }}>Platforms</span>
              &quot;). Your privacy on the Internet is of the utmost importance
              to us, so BIDRYDE is committed to protecting it to the greatest
              extent possible, reasonable, and commercially reasonable. Due to
              the fact that we collect certain types of information about You in
              order to provide, protect, maintain, and enhance our services, we
              believe that You should have a thorough understanding of the
              Policy governing the collection and use of this information, and
              we solicit Your full attention towards it.
            </p>
          </div>
          <div
            id="comp-lgxlxwjd"
            class="c9GqVL QxJLC3 comp-lgxlxwjd wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              You consent to the collection, storage, processing, and transfer
              of any or all of Your Personal Information and Non-Personal
              Information by BIDRYDE, as outlined in this Policy, by providing
              us with your Information or by utilising the facilities provided
              by the Platforms. You also represent and warrant that the
              collection, use, storage, and transfer of Your Information will
              not result in any loss or unjust enrichment to you or any other
              party.
            </p>
          </div>
          <div
            id="comp-lgxm27nz"
            class="c9GqVL QxJLC3 comp-lgxm27nz wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              This Policy is a legally binding agreement between You and
              BIDRYDE, whose Platform You use or access, or with whom You
              otherwise interact. This Policy is to be read in conjunction with
              the other terms and conditions of the Platform, including the
              Terms of Service Agreement and Fees Policy
            </p>
          </div>
          <div
            id="comp-lgxm42ay"
            class="c9GqVL QxJLC3 comp-lgxm42ay wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>PERSONAL INFORMATION COLLECTION, STORAGE AND UTILIZATION</h3>
          </div>
          <div
            id="comp-lgxm5ei7"
            class="c9GqVL QxJLC3 comp-lgxm5ei7 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              When You apply for or maintain an account with BIDRYDE, We collect
              certain personally identifiable information (&ldquo;Personal
              Information&rdquo;), such as: Your name, age, gender, photograph,
              contact preferences telephone number, mailing address, including
              but not limited to permanent and current residential addresses,
              e-mail address, financial information, internet protocol address,
              history of Your transactions ( booking and payment history), any
              other items of sensitive personal data or information, as such
              term is defined under the Information Technology (Reasonable
              Security Practices And Procedures And Sensitive Personal Data Of
              Information) Rules, 2011, which were enacted under the Information
              Technology Act, 2000, the identification code of Your
              communication device which You use to access the Platform, any
              other information that You provide during Your registration, use
              of availing of services via Platform, and other relevant documents
              such as a driving licence and additional address cum identity
              proofs, as prescribed under the Terms of service Agreement of
              BIDRYDE. By supplying information to establish a user account or
              complete Your user profile, You explicitly and freely accept this
              Policy, and You will be considered to have voluntarily accepted to
              authenticate Yourself with a government issued picture identity
              document that also includes Your address, other than a
              driver&#39;s license (hereinafter &quot;Government-issued
              ID&quot;), and You thus offer Your voluntary approval for seeding
              identifying data as contained in Government-issued ID to all
              Bidryde Service requirements and to provide Your identity
              information for authentication for the purpose of availing of the
              Services and to enforce any breach committed by you of the Terms
              of services Agreement through police, government/enforcement
              authority or court of law.
            </p>
          </div>
          <div
            id="comp-lgxmb5rj"
            class="c9GqVL QxJLC3 comp-lgxmb5rj wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              In pursuit of excellence in the services provided, a few more
              personal details that We gather are as follows:
            </p>
          </div>
          <div
            id="comp-lgxmchdk"
            class="c9GqVL QxJLC3 comp-lgxmchdk wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              <span style={{ fontWeight: "bold" }}>Vehicle Use Data:</span>{" "}
              Vehicles will contain hardware that collects and sends data on
              vehicle usage. This is done as a precaution against accident or
              theft, as well as to supply You with important services and data,
              such as information on other drivers.
            </p>
          </div>
          <div
            id="comp-lgxmhbap"
            class="c9GqVL QxJLC3 comp-lgxmhbap wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              <span style={{ fontWeight: "bold" }}>Location Tracking</span>: We
              follow the position of your car to avoid theft and to let us to
              find you in case of emergency, accident, lockout, etc. Your
              location information will be restricted to the BIDRYDE service,
              and we will make every effort not to make your location or
              movements&#39; public unless necessary by personal, medical, or
              legal (recovery or insurance) exigencies. As part of our service,
              the location of your car may be shared with insurance companies,
              the police, courts, tribunals, and other law enforcement
              authorities, in the course of an inquiry and/or accident claim, as
              well as to give help during an emergency. BIDRYDE also receives
              information on the location of each vehicle on the Platform.
            </p>
          </div>
          <div
            id="comp-lgxmjkds"
            class="c9GqVL QxJLC3 comp-lgxmjkds wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              <span style={{ fontWeight: "bold" }}>
                Driver and vehicle Information
              </span>
              : As a user of BIDRYDE&#39;s Platform, you permit us to acquire
              Your driver&#39;s record and vehicle travelled history report
              related to Your ride/trip from all relevant organizations and
              authorities. In addition, You permit all DMVs, RMVs, car
              mechanics, and any other entities and interested parties to
              disclose Your driving record and vehicle travel history to us
            </p>
          </div>
          <div
            id="comp-lgxmkkp9"
            class="c9GqVL QxJLC3 comp-lgxmkkp9 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              You may request that BIDRYDE stop using your personal information.
              By cancelling your account, You may withdraw Your permission to
              our future collection and use of Your information.
            </p>
          </div>
          <div
            id="comp-lgxmnsl5"
            class="c9GqVL QxJLC3 comp-lgxmnsl5 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              When you access and use our services, we gather data such as your
              phone number, email address, device manufacturer, and IP address.
              Some information may be shared with third party services in order
              to prevent fraud and provide a seamless payment and checkout
              process. The information may also be revealed to third-party
              vendors, such as call centres and customer support suppliers, in
              order to carry out Bidryde services. Please refer to the third
              party&#39;s privacy statement for more information.
            </p>
          </div>
          <div
            id="comp-lgxmpio8"
            class="c9GqVL QxJLC3 comp-lgxmpio8 wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>NON-PERSONAL INFORMATION COLLECTION AND UTILIZATION</h3>
          </div>
          <div
            id="comp-lgxmqnpk"
            class="c9GqVL QxJLC3 comp-lgxmqnpk wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              We also gather non-personal information, such as the browser You
              use, usage stats, and identifier technology. We are permitted to
              use, acquire, transmit, and disclose non-personal information for
              any reason. If We combine non-personal and personal information,
              the combined information will be considered as personal
              information so long as it remains combined.
            </p>
          </div>
          <div
            id="comp-lgxmtr0h"
            class="c9GqVL QxJLC3 comp-lgxmtr0h wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              <span style={{ fontWeight: "bold" }}>Aggregate Information</span>:
              We may share non-personally identifiable information (such as
              referring/exit pages, anonymous use statistics, and URLs, platform
              kinds, number of clicks, etc.) with third parties that are
              interested in gaining a better understanding of how particular
              BIDRYDE services are used.
            </p>
          </div>
          <div
            id="comp-lgxmvdsf"
            class="c9GqVL QxJLC3 comp-lgxmvdsf wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              On the Platform, third-party ad servers or ad networks may deliver
              advertising. Some third-party ad servers or ad networks may obtain
              Your IP address automatically when they deliver advertisements to
              your web browser. Moreover, they may employ other technologies
              (such as cookies, JavaScript, or web beacons) to assess the
              efficacy of their adverts and customise the advertising material.
              Please note, however, that if an advertiser requests BIDRYDE to
              display an ad to a specific audience and you reply to that ad, the
              advertiser or ad-server may assume that you meet the description
              of the population they are attempting to target. The BIDRYDE
              Policy does not apply to third-party advertisers, and we cannot
              monitor their activity
            </p>
          </div>
          <div
            id="comp-lgxn01xv"
            class="c9GqVL QxJLC3 comp-lgxn01xv wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>THIRD-PARTY LINKS</h3>
          </div>
          <div
            id="comp-lgxn4omj"
            class="c9GqVL QxJLC3 comp-lgxn4omj wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              This Platform may include connections to websites, products, and
              services from third parties. Information acquired by third
              parties, including location data and contact information, is
              subject to their privacy policies. We advise you to examine the
              privacy policies of these third parties. We cannot be held
              accountable for these policies.
            </p>
          </div>
          <div
            id="comp-lgxn5tpx"
            class="c9GqVL QxJLC3 comp-lgxn5tpx wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>INFORMATION EXCHANGE</h3>
          </div>
          <div
            id="comp-lgxnahmx"
            class="c9GqVL QxJLC3 comp-lgxnahmx wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              BIDRYDE exclusively shares Personal Information to third parties
              in the restricted situations outlined below:
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "40px" }}
            >
              i) To allow other organizations or individuals to process personal
              information on our behalf. We require that these parties agree to
              process personal information in accordance with Our instructions
              and this Policy, as well as any other relevant confidentiality and
              security measures.
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "40px" }}
            >
              ii) We have a strong belief that to gain access to, use, preserve,
              or disclose such information in order to
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "80px" }}
            >
              (a) comply with any applicable law, regulation, legal process, or
              enforceable governmental request, including to law enforcement and
              in response to a court order,
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "80px" }}
            >
              (b) detect, prevent, or otherwise address fraud, technical or
              security issues, and
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "80px" }}
            >
              (c) to enforce applicable terms and conditions of the Platform,
              including but not limited to Terms of service Agreement, Privacy
              Policy, and Fees Policy, which may be further extended to
              investigation of potential violations thereof, or
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "80px" }}
            >
              (d) to protect against harm to the rights, safety, or property of
              BIDRYDE, its Users, or the public as required or permitted by law.
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "40px" }}
            >
              iii) To safeguard and recover BIDRYDE&#39;s assets, such as
              vehicles and outstanding repayments.
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "40px" }}
            >
              iv) To defend ourselves against accusations from other parties. In
              the event that all or a portion of Our business or assets are sold
              or transferred, We retain the right to transmit any and all
              personal information that We hold about You.
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "40px" }}
            >
              v) We engage with third-party organizations to offer You with
              additional BIDRYDE-related services, such as ride-sharing,
              referral programmes, and parking advantages. When You purchase,
              register, or express interest in a product or service offered by a
              third party through BIDRYDE or that is sponsored on Our Platform,
              You consent to Our sharing your personal information with that
              third party. Participation in rewards programmes, discount offers,
              competitions, or other programs involving third parties permits
              BIDRYDE to disclose Your personal data with those parties. The use
              of Your information by a third party is governed by contracts and
              agreements between BIDRYDE and that third party. We only disclose
              information that is reasonably necessary to deliver additional
              services, and such information may be subject to additional
              privacy restrictions. You acknowledge that BIDRYDE is not
              accountable or responsible for the conduct or inactions of third
              parties by providing this information.
            </p>

            <p
              class="font_9 wixui-rich-text__text"
              style={{ marginLeft: "40px" }}
            >
              vi) BIDRYDE may transfer/disclose/share information with parties
              who support Our business by, for example, providing technical
              infrastructure services, analyzing how Our services are used,
              measuring the efficacy of advertisements, providing customer/buyer
              services, facilitating payments, or conducting academic research
              and surveys.
            </p>
          </div>
          <div
            id="comp-lgxo38pi"
            class="c9GqVL QxJLC3 comp-lgxo38pi wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>INFORMATION SECURITY, RETENTION AND DELETION</h3>
          </div>
          <div
            id="comp-lgxo5iht"
            class="c9GqVL QxJLC3 comp-lgxo5iht wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              We take safeguards, including administrative, technical, and
              physical procedures, to protect Your personal information from
              loss, misuse, or theft, as well as against destruction,
              disclosure, and unauthorised access. For this purpose, BIDRYDE
              conducts internal reviews of its data collection, storage, and
              processing practises and security measures, including appropriate
              encryption and physical security measures to prevent unauthorised
              access to systems where BIDRYDE stores Your Personal Information;
              provided, however, that Your right to claim damages shall be
              limited to the right to claim only statutory damages under the
              Information Technology Act, 2000, and You hereby waive and release
              BIDRYDE from any claim of damages under contract or under tort.
            </p>
          </div>
          <div
            id="comp-lgxo6md3"
            class="c9GqVL QxJLC3 comp-lgxo6md3 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              When You use Our services or publish on the Platform, some of Your
              Personal Information is available to other users and can be read,
              collected, or used by them. You are responsible for any Personal
              Information you submit in these situations. If You submit Your
              name and email address on the Platform, for instance, Your
              information is accessible to the public. In addition, you are
              responsible for maintaining the secrecy of your account and
              password and for restricting access to your computer; you also
              agree to bear the responsibility for all actions that occur under
              your account or password.
            </p>
          </div>
          <div
            id="comp-lgxo93yo"
            class="c9GqVL QxJLC3 comp-lgxo93yo wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              BIDRYDE may share Your Information with third parties according to
              a confidentiality agreement that, among other things, prohibits
              such third parties from releasing the Information except for the
              purposes outlined in the particular confidentiality agreements.
              Even so, BIDRYDE is not liable for any security flaws or the
              activities of any third parties that acquire Your Personal
              Information. BIDRYDE is not responsible for any loss or damage
              incurred as a result of Your disclosure of Personal Information to
              third parties (including any third party platforms, even if links
              to such third party platforms are provided on the Platform)
            </p>
          </div>
          <div
            id="comp-lgxoa1ev"
            class="c9GqVL QxJLC3 comp-lgxoa1ev wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              BIDRYDE shall not be liable for any loss, damage, or misuse of
              Your Personal Information if such loss, damage, or misuse is
              caused by a Force Majeure Event, notwithstanding anything to the
              effect in this Policy or elsewhere (as defined below).
            </p>
          </div>
          <div
            id="comp-lgxobbmg"
            class="c9GqVL QxJLC3 comp-lgxobbmg wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              A &quot;Force Majeure Event&quot; shall mean any event that is
              beyond the reasonable control of BIDRYDE and shall include,
              without limitation, sabotage, fire, flood, explosion, acts of God,
              civil commotion, strikes or industrial action of any kind, riots,
              insurrection, war, acts of government, computer hacking,
              unauthorised access to computer, computer system or computer
              network, computer crashes, breach of security and encryption
              (provided beyond reasonable commercial control of BIDRYDE), power
              or electricity failure or unavailability of adequate power or
              electricity.
            </p>
          </div>
          <div
            id="comp-lgxoc99t"
            class="c9GqVL QxJLC3 comp-lgxoc99t wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              While We will endeavour to take all reasonable and appropriate
              steps to secure and prevent unauthorised access to any Personal
              Information that We hold about You, You acknowledge that the
              internet and computer networks are not completely secure and that
              We cannot provide absolute assurance regarding the security of
              Your Personal Information. Please use caution while deciding which
              Personal information to disclose over the Service.
            </p>
          </div>
          <div
            id="comp-lgxofc0v"
            class="c9GqVL QxJLC3 comp-lgxofc0v wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              You consent to the retention of all Personal Information for as
              long as necessary for the purpose or as required by relevant law,
              whichever is later. Non-Personally Identifiable Information will
              be kept forever.
            </p>
          </div>
          <div
            id="comp-lgxogx68"
            class="c9GqVL QxJLC3 comp-lgxogx68 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              If you want to delete your Personal Information from our Platform,
              send us an email at{" "}
              <a data-auto-recognition="true" href="mailto:support@bidryde.in">
                support@bidryde.in
              </a>
              . We will ask you to include your first name, last name, user
              name/screen name (if you have one), email address associated with
              our Platform, the reason you want to delete the content, and the
              date(s) of the content you want to delete (if only specific
              content needs to be deleted). If you can&#39;t give us this
              information, we might not be able to handle your request to delete
              your information. Please give us up to 30 business days to handle
              your request to delete your account.
            </p>
          </div>
          <div
            id="comp-lgxoi7aw"
            class="c9GqVL QxJLC3 comp-lgxoi7aw wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>COOKIES POLICY</h3>
          </div>
          <div
            id="comp-lgxojf13"
            class="c9GqVL QxJLC3 comp-lgxojf13 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              Several technologies, including &quot;cookies,&quot; are used to
              gather non-personally identifiable information. A cookie is a
              piece of data that any platform may transmit to Your browser,
              which may subsequently be saved as an anonymous tag that
              identifies Your device but not You. To improve Our Service,
              certain BIDRYDE sites utilise cookies, delivered by BIDRYDE or its
              third party partners, or other technologies. You may restrict the
              impact of cookies using your browser settings; however, if cookies
              are disabled, certain features of BIDRYDE&#39;s Service may not
              function correctly.
            </p>
          </div>
          <div
            id="comp-lgxol1l9"
            class="c9GqVL QxJLC3 comp-lgxol1l9 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              Moreover, we may use Web beacons or other technologies, sometimes
              in combination with cookies, to improve Our Service on a number of
              sites of BIDRYDE&#39;s Platform. A non-identifiable trace of a
              visitor&#39;s visit to a page on the BIDRYDE website is produced
              and stored, and may be processed by us or by Our suppliers. You
              may stop some of these capabilities by disabling cookies in your
              web browser settings. Web beacon and other technologies will still
              detect visits to these sites, but the alerts they create are
              discarded and cannot be connected with other non-identifiable
              cookie information.
            </p>
          </div>
          <div
            id="comp-lgxopo13"
            class="c9GqVL QxJLC3 comp-lgxopo13 wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>CHANGES TO OUR PRIVACY POLICY</h3>
          </div>
          <div
            id="comp-lgxoqty6"
            class="c9GqVL QxJLC3 comp-lgxoqty6 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              Please note that this Policy is subject to modification at any
              moment. Changes to the Policy shall be posted on the Platform
              without prior notification to You. Review the Policy each time You
              access the Platform. By continuing to use the Platform, You
              implicitly agree to the terms of any revised/updated Policy.
            </p>
          </div>
          <div
            id="comp-lgxorrbz"
            class="c9GqVL QxJLC3 comp-lgxorrbz wixui-rich-text"
            data-testid="richTextElement"
          >
            <h3>MISCELLANEOUS</h3>
          </div>
          <div
            id="comp-lgxosyn2"
            class="c9GqVL QxJLC3 comp-lgxosyn2 wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              While BIDRYDE may store any correspondence submitted by You, it
              has no intention of collecting or storing information from minors
              under 15 years of age. BIDRYDE retains the right, at its sole
              discretion, to delete or modify material, reject service,
              terminate accounts, or cancel plans or orders.
            </p>
          </div>
          <div
            id="comp-lgym7rfg"
            class="c9GqVL QxJLC3 comp-lgym7rfg wixui-rich-text"
            data-testid="richTextElement"
          >
            <p>
              If You notice any discrepancies or have any complaints regarding
              the collection, storage, use, disclosure, and transfer of Your
              Personal Information in accordance with this Policy or other
              conditions of BIDRYDE&#39;s Terms of Service Agreement, Privacy
              Policy, Fees Policy, etc., please contact: Mr. Bhanu Prakash is
              the grievance officer assigned under the Information Technology
              Act of 2000. His email address is{" "}
              <a
                data-auto-recognition="true"
                href="mailto:compliances@bidryde.in"
              >
                compliances@bidryde.in
              </a>
              .
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default PrivacyPolicy;
